// Code generated by protoc-gen-go. DO NOT EDIT.
// source: head.proto

package packet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Head struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Head) Reset()         { *m = Head{} }
func (m *Head) String() string { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()    {}
func (*Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d0bdc0adf338bad, []int{0}
}

func (m *Head) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Head.Unmarshal(m, b)
}
func (m *Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Head.Marshal(b, m, deterministic)
}
func (m *Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Head.Merge(m, src)
}
func (m *Head) XXX_Size() int {
	return xxx_messageInfo_Head.Size(m)
}
func (m *Head) XXX_DiscardUnknown() {
	xxx_messageInfo_Head.DiscardUnknown(m)
}

var xxx_messageInfo_Head proto.InternalMessageInfo

func (m *Head) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TheTestMsg struct {
	A                    int32    `protobuf:"varint,1,opt,name=A,proto3" json:"A,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	C                    string   `protobuf:"bytes,3,opt,name=C,proto3" json:"C,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TheTestMsg) Reset()         { *m = TheTestMsg{} }
func (m *TheTestMsg) String() string { return proto.CompactTextString(m) }
func (*TheTestMsg) ProtoMessage()    {}
func (*TheTestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d0bdc0adf338bad, []int{1}
}

func (m *TheTestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TheTestMsg.Unmarshal(m, b)
}
func (m *TheTestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TheTestMsg.Marshal(b, m, deterministic)
}
func (m *TheTestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TheTestMsg.Merge(m, src)
}
func (m *TheTestMsg) XXX_Size() int {
	return xxx_messageInfo_TheTestMsg.Size(m)
}
func (m *TheTestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TheTestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TheTestMsg proto.InternalMessageInfo

func (m *TheTestMsg) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *TheTestMsg) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *TheTestMsg) GetC() string {
	if m != nil {
		return m.C
	}
	return ""
}

func init() {
	proto.RegisterType((*Head)(nil), "packet.Head")
	proto.RegisterType((*TheTestMsg)(nil), "packet.TheTestMsg")
}

func init() { proto.RegisterFile("head.proto", fileDescriptor_1d0bdc0adf338bad) }

var fileDescriptor_1d0bdc0adf338bad = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x48, 0x4d, 0x4c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x48, 0x4c, 0xce, 0x4e, 0x2d, 0x51, 0x92,
	0xe2, 0x62, 0xf1, 0x48, 0x4d, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0xf1, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xcc, 0xb8, 0xb8, 0x42, 0x32, 0x52, 0x43, 0x52,
	0x8b, 0x4b, 0x7c, 0x8b, 0xd3, 0x85, 0x78, 0xb8, 0x18, 0x1d, 0xc1, 0xd2, 0xac, 0x41, 0x8c, 0x8e,
	0x20, 0x9e, 0x93, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x73, 0x10, 0xa3, 0x13, 0x88, 0xe7, 0x2c, 0xc1,
	0x0c, 0xd6, 0xca, 0xe8, 0x9c, 0xc4, 0x06, 0xb6, 0xc2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x47,
	0xa1, 0xca, 0x98, 0x70, 0x00, 0x00, 0x00,
}
